Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
